### ISSUE TITLE
REGEX: no whitespaces

### ISSUE THREAD

**Issue by seanvree** [DrRoach/FormValidation#1] opened 2018-03-06 20:00 UTC
hey man, good job on this. 

Question:

Trying to produce an error if the input contains white spaces ... using this:

```
fv-advanced='{"regex": "/^\s$/;", "message": "This field cannot contain spaces."}' 
``

But I'm getting the following error:

```
VM389:1 Uncaught SyntaxError: Unexpected token s in JSON at position 15
    at JSON.parse (<anonymous>)
    at HTMLInputElement.<anonymous> (VM375 formValidation.js:33)
    at HTMLInputElement.dispatch (jquery.min.js:2)
    at HTMLInputElement.y.handle (jquery.min.js:2)
```

Any tips?

thanks,

**Comment by DrRoach** [comment] 2018-03-06 20:24
Hello,
I think the problem is the `;` after the closing `/` in your regex.
Try changing `"/^\s$/;"` to `"/^\s$/"`. If that doesn't work, I'll have a closer look though when I get to a computer

**Comment by seanvree** [comment] 2018-03-06 20:26
Yeah, I tried removing that and a couple other combos, no dice.  No worries my man. LMK

**Comment by DrRoach** [comment] 2018-03-09 15:09
Hi, sorry about the long delay i getting back to you about this!!

Please see this commit: 7cf94b0442b1b573ab6d49a48a6d4ca58e827612

Firstly, I have added a regex_reverse option which will throw an invalid input if the regular expression is matched, rather than if it is not matched.

Secondly, there's some strange goings on with regards to the `\` in the regular expression. The fix for this is to use double slash.

So to check to make sure that there are no whitespaces in your input you will need:

```
fv-advanced='{"regex": "\\s", "regex_reverse": true, "message": "This field cannot contain spaces."}' 
```

Hope this helps and if you have any more problems feel free to ask :)

**Closed as completed by DrRoach** 2018-03-09 15:09 UTC

**Comment by seanvree** [comment] 2018-03-09 16:00
@DrRoach 

Hey, no problem man. 

However, i think it's backwards tho.  It's validating only when white spaces are PRESENT.  Instead of the other way around. 

 I tried changing to "regex_reverse": false,   but that didn't work. 


![image](https://user-images.githubusercontent.com/8906637/37216487-bc1c5b72-236f-11e8-97cc-e582cbc34063.png)


![image](https://user-images.githubusercontent.com/8906637/37216497-c47c9bce-236f-11e8-8052-2f8e7f2e0fab.png)

**Comment by DrRoach** [comment] 2018-03-09 16:23
Have you tried with setting `regex_reverse` to `true`?

The way that I see the regex's working is that if the pattern is there then our input is valid. Hence why when reversing that, if the pattern exists our input is invalid.

I'm not sure if this is the best implementation of reverse or whether it should be the other way around but for now I guess this is how it'll be

**Comment by seanvree** [comment] 2018-03-09 16:26
Yes. I tried setting it to true and removing the regex_reverse string all together. Still backwards.

**Comment by DrRoach** [comment] 2018-03-09 16:31
Hmm that is strange indeed. I've created two inputs, the first with `reverse = true` and the second with `reverse = false`.

![image](https://user-images.githubusercontent.com/5173524/37218043-381eaea4-23b7-11e8-9df3-e96a411ce88a.png)

![image](https://user-images.githubusercontent.com/5173524/37218269-d1620b42-23b7-11e8-9467-b9ba64eeb8ff.png)


Could I ask you to do the same and also post your input code? Maybe I'm missing something

**Comment by seanvree** [comment] 2018-03-09 16:37
@DrRoach  yeah, no problem:

```

<form id="userForm">

    <i class='fa fa-fw fa-folder-open'> </i> 
    <input type='text' name='datadir' title="Cannot contain spaces & must contain trailing slash" fv-advanced='{"regex": "\\s", "regex_reverse": true, "message": "This field cannot contain spaces."}' fv-not-empty=" This field can't be empty" id="datadir" autocomplete="off" placeholder=' Data dir path' required>

    <div>
        <input type='submit' id="datadirbtn" class="btn btn-primary" value='Create' />
    </div>

</form>
```

**Comment by DrRoach** [comment] 2018-03-09 16:44
That's strange, it seems to be working okay for me, have you got the latest commits?

On a side note, I've noticed a bug where only the first validation check is ran and will aim to fix this asap. #4

**Comment by seanvree** [comment] 2018-03-09 16:50
dude @DrRoach  I'm sorry brother, looks like it was a caching issue.  I cleared all cache and pretty much had to shut down my box to get it to work. 

Thanks brother. 

FYI, implementing it on this project:

https://github.com/Monitorr/Monitorr

We'll throw you some credit.

**Comment by DrRoach** [comment] 2018-03-09 19:37
Haha no worries at all, I've been there myself, glad that it's working now though.

Ahh looks like a cool project, I'll have to  check it out in the future, thank you for that!!

**Comment by seanvree** [comment] 2018-03-10 06:34
NP, looking forward to when you can get that other bug worked out!  

https://github.com/DrRoach/FormValidation/issues/4

**Comment by seanvree** [comment] 2018-03-10 18:36
@DrRoach  I HATE to come back at ya with another question, but does your script run all regex patterns or do you have to code them in depending on the value? 

I'm trying to get another validation to work on the same field but with another regex pattern which DOES work with the jquery. 

```
var re = /.*[\\//]+$/;
```

I think the leading and trailing slashes can be removed however.

This pattern essentially ensures the last character is a backstalsh or a forwardslash. 

Not sure if this was something easy...if not, no biggie.

-SV
